#!/usr/bin/env bash

# Quick Start: SMS Sending

echo "🚀 Church Communication Platform - SMS Setup"
echo "=============================================="
echo ""
echo "✅ COMPLETED:"
echo "  • Backend created (Express + Twilio)"
echo "  • SMS API endpoint ready"
echo "  • Frontend integrated"
echo "  • Credentials secured in .env"
echo ""
echo "📋 YOUR CREDENTIALS (Saved & Secure):"
echo "  Account SID: [SECURE]"
echo "  Twilio Phone: [SECURE]"
echo "  Auth Token: 🔒 (stored in backend/.env)"
echo ""
echo "🎯 TO START SENDING SMS NOW:"
echo ""
echo "  Terminal 1 - Backend:"
echo "  $ cd backend"
echo "  $ npm install"
echo "  $ npm run dev"
echo ""
echo "  Terminal 2 - Frontend:"
echo "  $ npm run dev"
echo ""
echo "  Then open: http://localhost:5173"
echo ""
echo "✉️  SEND YOUR FIRST SMS:"
echo "  1. Log in (admin@churchcomm.ng / admin123)"
echo "  2. Go to Contacts, add a real Nigerian phone"
echo "  3. Go to Dashboard"
echo "  4. Type message, select SMS"
echo "  5. Click Send"
echo "  6. Check Twilio Console for delivery: https://www.twilio.com/console/sms/logs"
echo ""
echo "💬 FOR WHATSAPP (Next Step):"
echo "  See: WHATSAPP_SETUP.md"
echo ""
echo "📚 MORE INFO:"
echo "  Backend Setup: backend/README.md"
echo "  SMS Details: SMS_SETUP_COMPLETE.md"
echo "  WhatsApp Guide: WHATSAPP_SETUP.md"
echo ""
