import { uid } from "./utils/phone";
import type { Admin, Contact, Group, Template } from "./types";

const LS_KEY = "churchcomm.v1";

export type StoreShape = {
  currentAdminId: string | null;
  rememberMe: boolean;
  failedAttempts: number;
  lockedUntil: number | null;
  admins: Admin[];
  contacts: Contact[];
  templates: Template[];
  groups: Group[];
  broadcastIds: string[]; // broadcasts stored separately due to size
};

const GROUP_COLORS = [
  "#6366f1",
  "#f59e0b",
  "#10b981",
  "#ef4444",
  "#8b5cf6",
  "#0ea5e9",
  "#ec4899",
  "#14b8a6",
];

export function seedData(): StoreShape {
  return {
    currentAdminId: null,
    rememberMe: false,
    failedAttempts: 0,
    lockedUntil: null,
    admins: [
      {
        id: uid(),
        email: "admin@churchcomm.ng",
        password: "admin123",
        name: "Admin",
        role: "super_admin",
      },
      {
        id: uid(),
        email: "office@churchcomm.ng",
        password: "office123",
        name: "Admin 2",
        role: "admin",
      },
    ],
    contacts: [
      {
        id: uid(),
        firstName: "Elder Serge",
        lastName: "",
        phoneNumber: "+237679931488",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Abigail",
        lastName: "",
        phoneNumber: "+237671112872",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Ma Hannah",
        lastName: "",
        phoneNumber: "+237652650207",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Nerisa",
        lastName: "",
        phoneNumber: "+237650471261",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Ma Grace",
        lastName: "",
        phoneNumber: "+237677171512",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Ma Marbel",
        lastName: "",
        phoneNumber: "+237678693303",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Ma Pamela",
        lastName: "",
        phoneNumber: "+237651713152",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Junabelle",
        lastName: "",
        phoneNumber: "+237670335435",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Ashu",
        lastName: "",
        phoneNumber: "+237673753450",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Dec. Felicity",
        lastName: "",
        phoneNumber: "+237676344500",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Dimobel",
        lastName: "",
        phoneNumber: "+237673886641",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Rita",
        lastName: "",
        phoneNumber: "+237653713000",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Miracle",
        lastName: "",
        phoneNumber: "+237683165760",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Ronaldo",
        lastName: "",
        phoneNumber: "+237653677617",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Rose",
        lastName: "",
        phoneNumber: "+237680054696",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Emerencia",
        lastName: "",
        phoneNumber: "+237679793707",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Vanessa",
        lastName: "",
        phoneNumber: "+237672476782",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Teriel",
        lastName: "",
        phoneNumber: "+237673356549",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Ramson",
        lastName: "",
        phoneNumber: "+237653417366",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Brandy",
        lastName: "",
        phoneNumber: "+237682396514",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Franka",
        lastName: "",
        phoneNumber: "+237650359501",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Shama",
        lastName: "",
        phoneNumber: "+237682108398",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Ma Vivian",
        lastName: "",
        phoneNumber: "+237681023135",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Ma Doris",
        lastName: "",
        phoneNumber: "+237674225248",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Caleb",
        lastName: "",
        phoneNumber: "+237676741870",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Yvette",
        lastName: "",
        phoneNumber: "+237678952652",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Mary",
        lastName: "",
        phoneNumber: "+237650415624",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Inocent",
        lastName: "",
        phoneNumber: "+237653013579",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Elizabeth",
        lastName: "",
        phoneNumber: "+237671659072",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Mummy Syvian",
        lastName: "",
        phoneNumber: "+237650935046",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Favour W",
        lastName: "",
        phoneNumber: "+237679559084",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Confidence",
        lastName: "",
        phoneNumber: "+237652156589",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Esther",
        lastName: "",
        phoneNumber: "+237670933143",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Faith",
        lastName: "",
        phoneNumber: "+237671606715",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Abenego",
        lastName: "",
        phoneNumber: "+237679769999",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Hilda",
        lastName: "",
        phoneNumber: "+237688559753",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Minet",
        lastName: "",
        phoneNumber: "+237679983224",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Shanis",
        lastName: "",
        phoneNumber: "+237675034033",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Linda",
        lastName: "",
        phoneNumber: "+237651059252",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Sis Paoula",
        lastName: "",
        phoneNumber: "+237650136288",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Bless",
        lastName: "",
        phoneNumber: "+237671063339",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
      {
        id: uid(),
        firstName: "Br Christian",
        lastName: "",
        phoneNumber: "+237652070823",
        whatsappEnabled: true,
        group: "General",
        email: "",
        status: "active",
        dateAdded: new Date().toISOString(),
        notes: "",
      },
    ],
    templates: [
      {
        id: uid(),
        name: "Sunday Service Reminder",
        title: "Sunday Service",
        body: "Beloved, join us this Sunday at 9:00 AM for worship and the Word. Come expecting a mighty move of God! 🙏",
        createdAt: new Date().toISOString(),
      },
      {
        id: uid(),
        name: "Midweek Bible Study",
        title: "Bible Study Tonight",
        body: "Reminder: Midweek Bible Study tonight at 6:30 PM. Topic: Walking in the Spirit. Don't miss it! 📖",
        createdAt: new Date().toISOString(),
      },
      {
        id: uid(),
        name: "Emergency Prayer Alert",
        title: "Prayer Needed",
        body: "Urgent prayer request — please lift up our brother/sister in prayer right now. God is faithful.",
        createdAt: new Date().toISOString(),
      },
    ],
    groups: [
      { id: uid(), name: "General", color: GROUP_COLORS[0], createdAt: new Date().toISOString() },
      { id: uid(), name: "Choir", color: GROUP_COLORS[1], createdAt: new Date().toISOString() },
      { id: uid(), name: "Youth", color: GROUP_COLORS[2], createdAt: new Date().toISOString() },
      { id: uid(), name: "Elders", color: GROUP_COLORS[3], createdAt: new Date().toISOString() },
      { id: uid(), name: "Women's Fellowship", color: GROUP_COLORS[4], createdAt: new Date().toISOString() },
      { id: uid(), name: "Ushers", color: GROUP_COLORS[5], createdAt: new Date().toISOString() },
    ],
    broadcastIds: [],
  };
}

export function loadStore(): StoreShape {
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) {
      const seeded = seedData();
      localStorage.setItem(LS_KEY, JSON.stringify(seeded));
      return seeded;
    }
    return JSON.parse(raw) as StoreShape;
  } catch {
    return seedData();
  }
}

export function saveStore(store: StoreShape): void {
  try {
    localStorage.setItem(LS_KEY, JSON.stringify(store));
  } catch {
    // noop
  }
}

export function resetStore(): StoreShape {
  const fresh = seedData();
  localStorage.setItem(LS_KEY, JSON.stringify(fresh));
  return fresh;
}